export default {
  GET_USERS: 'GET_USERS',
  GET_USERS_START: 'GET_USERS_START',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILURE: 'GET_USERS_FAILURE',
  UPDATE_USER: 'UPDATE_USER',
  CHANGE_FILTER: 'CHANGE_FILTER',
};
